package com.llmwiki.domain.example.entity;

import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class EntityExampleTest {

    @Test
    void shouldCreateEntityExampleWithBuilder() {
        EntityExample example = EntityExample.builder()
                .name("Java Example")
                .description("Example for Java programming language")
                .exampleText("Java is a programming language created by James Gosling.")
                .extractionData("[{\"extractionClass\":\"TECH\",\"extractionText\":\"Java\",\"description\":\"Programming language\"}]")
                .entityType("ENTITY")
                .build();

        assertNotNull(example);
        assertEquals("Java Example", example.getName());
        assertEquals("Example for Java programming language", example.getDescription());
        assertEquals("Java is a programming language created by James Gosling.", example.getExampleText());
        assertEquals("[{\"extractionClass\":\"TECH\",\"extractionText\":\"Java\",\"description\":\"Programming language\"}]", example.getExtractionData());
        assertEquals("ENTITY", example.getEntityType());
        assertFalse(example.getDeleted());
    }

    @Test
    void shouldSetCreatedAtOnPrePersist() {
        EntityExample example = new EntityExample();
        assertNull(example.getCreatedAt());
        assertNull(example.getUpdatedAt());

        example.onCreate();

        assertNotNull(example.getCreatedAt());
        assertNotNull(example.getUpdatedAt());
    }

    @Test
    void shouldUpdateUpdatedAtOnPreUpdate() {
        EntityExample example = new EntityExample();
        example.onCreate();
        Instant originalUpdatedAt = example.getUpdatedAt();

        // Small delay to ensure different timestamp
        try { Thread.sleep(10); } catch (InterruptedException ignored) {}

        example.onUpdate();

        assertNotNull(example.getUpdatedAt());
        // UpdatedAt should be equal or after the original
        assertTrue(!example.getUpdatedAt().isBefore(originalUpdatedAt));
    }

    @Test
    void shouldSupportConceptType() {
        EntityExample example = EntityExample.builder()
                .name("OOP Concept")
                .exampleText("Object-oriented programming concepts.")
                .extractionData("[{\"extractionClass\":\"CONCEPT\",\"extractionText\":\"OOP\"}]")
                .entityType("CONCEPT")
                .build();

        assertEquals("CONCEPT", example.getEntityType());
    }

    @Test
    void shouldSupportSoftDelete() {
        EntityExample example = EntityExample.builder()
                .name("Test")
                .exampleText("Text")
                .extractionData("[]")
                .entityType("ENTITY")
                .build();

        assertFalse(example.getDeleted());
        example.setDeleted(true);
        assertTrue(example.getDeleted());
    }

    @Test
    void shouldGenerateId() {
        EntityExample example = new EntityExample();
        // UUID is generated by JPA; in test we just verify the field exists
        assertNull(example.getId());
        example.setId(UUID.randomUUID());
        assertNotNull(example.getId());
    }

    @Test
    void shouldHandleNullExtractionData() {
        EntityExample example = EntityExample.builder()
                .name("Empty Example")
                .exampleText("Text with no extractions.")
                .extractionData(null)
                .entityType("ENTITY")
                .build();

        assertNull(example.getExtractionData());
    }

    @Test
    void shouldBeActiveByDefault() {
        EntityExample example = new EntityExample();
        assertFalse(example.getDeleted());
    }
}
